In [2]:
import pandas as pd

In [18]:
pd.Series([1,"kk",3,4,5])

0     1
1    kk
2     3
3     4
4     5
dtype: object

In [28]:
seri = pd.Series([1,"kkl",11.8,4,5])

In [30]:
type(seri)

pandas.core.series.Series

In [32]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [34]:
seri.dtype

dtype('O')

In [36]:
seri.ndim

1

In [38]:
seri.values

array([1, 'kkl', 11.8, 4, 5], dtype=object)

In [44]:
seri.head(3)

0       1
1     kkl
2    11.8
dtype: object

In [46]:
seri.tail(3)

2    11.8
3       4
4       5
dtype: object

In [48]:
#indeks isimlendirme

In [54]:
pd.Series([12,43,44,2112,0,5], index = [1,3,5,7,9,11])

1       12
3       43
5       44
7     2112
9        0
11       5
dtype: int64

In [56]:
pd.Series([12,43,44,2112,0,5], index = ["a","b","c","d","e","f"])

a      12
b      43
c      44
d    2112
e       0
f       5
dtype: int64

In [58]:
seri = pd.Series([12,43,44,2112,0,5], index = ["a","b","c","d","e","f"])

In [60]:
seri["a"]

12

In [62]:
seri["a":"c"]

a    12
b    43
c    44
dtype: int64

In [64]:
#sozluk uzerinden liste olusturma

In [66]:
sozluk = {"reg":10, "log":11, "cart": 12}

In [68]:
seri = pd.Series(sozluk)

In [72]:
seri

reg     10
log     11
cart    12
dtype: int64

In [74]:
#iki seriyi birleştirerek seri oluşturma

In [77]:
pd.concat([seri, seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

In [ ]:
pd.concat

## Eleman işlemleri

In [7]:
import numpy as np
import pandas as pd

In [5]:
a = np.array([1,2,33,444,75])

In [9]:
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [13]:
seri[0]

1

In [17]:
seri[0:3]

0     1
1     2
2    33
dtype: int32

In [19]:
seri = pd.Series([24,5,23,65], index= ["reg","loj","cart", "rf"])

In [21]:
seri

reg     24
loj      5
cart    23
rf      65
dtype: int64

In [23]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [27]:
seri.keys

<bound method Series.keys of reg     24
loj      5
cart    23
rf      65
dtype: int64>

In [29]:
list(seri.items())

[('reg', 24), ('loj', 5), ('cart', 23), ('rf', 65)]

In [33]:
print(seri.values)

[24  5 23 65]


In [35]:
#eleman sorgulama

In [37]:
"reg" in seri

True

In [39]:
"Reg" in seri

False

In [41]:
seri["reg"]

24

In [43]:
#fancy eleman

In [45]:
seri[["rf", "reg"]]

rf     65
reg    24
dtype: int64

In [49]:
seri["reg"] = 30

In [51]:
seri

reg     30
loj      5
cart    23
rf      65
dtype: int64

In [53]:
seri["reg":"loj"]

reg    30
loj     5
dtype: int64

## Pandas DataFrame oluşturma

In [56]:
#pandasta farklı veriler birlikte tutulabilir numpy yapamıyordu

In [58]:
import pandas as pd

In [60]:
l = [1,2,39,67,90]

In [62]:
l

[1, 2, 39, 67, 90]

In [64]:
pd.DataFrame(l, columns =["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [70]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
pd.DataFrame(m, columns =["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [74]:
#df isimlendirme

In [76]:
df = pd.DataFrame(m, columns =["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [80]:
df.columns = ("deg1", "deg2", "deg3")

In [83]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [85]:
type(df)

pandas.core.frame.DataFrame

In [87]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [89]:
df.shape

(3, 3)

In [99]:
df.ndim
#her zaman 2dir

2

In [93]:
df.size

9

In [95]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
type(df.values)

numpy.ndarray

In [105]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [107]:
df.head(1)

deg1  deg2  deg3
0     1     2     3

In [109]:
a = np.array([1,2,3,4,5])

In [115]:
pd.DataFrame(a, columns = ["d1"])

d1
0   1
1   2
2   3
3   4
4   5